<a href="https://colab.research.google.com/github/Abinayak03/Machine_learning/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

You are a data scientist / AI engineer at a meteorological consulting firm. You have been provided with a dataset named **"weather_data.csv"**, which includes detailed records of various weather conditions. The dataset comprises the following columns:

- **`hours_sunlight:`** The total number of hours of sunlight received in a day.
- **`humidity_level:`** The humidity level as a percentage.
- **`daily_temperature:`** The temperature recorded at the end of the day in degrees Celsius.

Your task is to use this dataset to build a linear regression model to predict the daily temperature based on the hours of sunlight and humidity level.

**Import Necessary Libraries**

In [1]:
#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


### Task 1: Train a Linear Regression with Single Variable

1. Import the data from the "weather_data.csv" file and store it in a variable df.
2. Display the number of rows and columns in the dataset.
3. Display the first few rows of the dataset to get an overview.
4. Create a Linear Regression model and fit it using only the `hours_sunlight` variable to predict `daily_temperature`.
5. Print the model's coefficient and intercept.
6. Predict the daily temperature with the following hours of sunlight:
   - 5 hours
   - 8 hours
   - 12 hours

In [2]:
# Step 1: Import the data from the "weather_data.csv" file and store it in a variable 'df'
df=pd.read_csv("weather_data.csv")

# Step 2: Display the number of rows and columns in the dataset
print(df.shape)

# Step 3: Display the first few rows of the dataset to get an overview
df.head()

(49, 3)


hours_sunlight  humidity_level  daily_temperature
0            10.5              65               22.3
1             9.2              70               21.0
2             7.8              80               18.5
3             6.4              90               17.2
4             8.1              75               19.4

In [4]:
# Step 4: Create a Linear Regression model and fit it using only the 'hours_sunlight' variable to predict 'daily_temperature'
model=LinearRegression()
model.fit(df[['hours_sunlight']],df['daily_temperature'])

LinearRegression()

In [5]:
# Step 5: Print the model's coefficient and intercept
model.coef_,model.intercept_

(array([1.36753934]), 8.533832092006133)

In [9]:
# Step 6: Predict the daily temperature for the following hours of sunlight: 5, 8, and 12
hours=[[5],[8],[12]]
model.predict(hours)

# Print the predicted temperatures


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.37152878, 19.4741468 , 24.94430415])

### Task 2: Train a Linear Regression with Multiple Variable

- Create a Linear Regression model and fit it using both `hours_sunlight` and `humidity_level` variables to predict `daily_temperature`.
- Print the model's coefficients and intercept.
- Predict the daily temperature for the following conditions:
    - Hours of sunlight: 5 hours, Humidity level: 60%
    - Hours of sunlight: 8 hours, Humidity level: 75%
    - Hours of sunlight: 12 hours, Humidity level: 50%

In [10]:
#Step1: Create a Linear Regression model and fit it using both 'hours_sunlight' and 'humidity_level' variables to predict 'daily_temperature'
model2=LinearRegression()
model2.fit(df[['hours_sunlight','humidity_level']],df['daily_temperature'])

LinearRegression()

In [11]:
#Step2: Print the model's coefficients and intercept
model2.coef_,model2.intercept_

(array([ 1.09803993, -0.05430624]), 14.833402427458843)

In [15]:
# Step3: Predict the daily temperature for the following conditions:
# Hours of sunlight: 5 hours, Humidity level: 60%
# Hours of sunlight: 8 hours, Humidity level: 75%
# Hours of sunlight: 12 hours, Humidity level: 50%
test=pd.DataFrame({'hours_sunlight':[5,8,12],'humidity_level':[60,75,50]})
model2.predict(test)

for hours,humidity,temp in zip(test['hours_sunlight'],test['humidity_level'],model2.predict(test)):
    print(f"For {hours} hours of sunlight and {humidity}% humidity, the predicted temperature is {temp:.2f} degrees Celsius.")

For 5 hours of sunlight and 60% humidity, the predicted temperature is 17.07 degrees Celsius.
For 8 hours of sunlight and 75% humidity, the predicted temperature is 19.54 degrees Celsius.
For 12 hours of sunlight and 50% humidity, the predicted temperature is 25.29 degrees Celsius.
